version: '1.0'
services:
  - name: db-klantnaam
    type: postgres
    version: 9.6
    configuration: StandAlone
    ports:
      - 5432
    env:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: null
    remoteAccess: false
    deployTo:
      - odoo

  - name: odoo-klantnaam
    type: docker
    image: codeagency/odoo-enterprise
    version: 11.0
    source: null
    ports:
      - 8069
      - 8071
    remoteAccess: false
    env:
      HOST: "{{=service('db').getMasterAlias()}}"
      PORT: "{{=service('db').getMainPort()}}"
      USER: odoo
      PASSWORD: "{{=service('db').getEnv('POSTGRES_PASSWORD')}}"
    volumes:
      - directory: /var/lib/odoo
    volumesUID: 101
    startCommand: --addons $MAIN_PATH,/mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons  -i web_enterprise
    deployTo:
      - odoo

  - name: nginx-klantnaam
    type: nginx
    version: 1.13
    ports:
      - 80
      - 443
    remoteAccess: true
    serviceFiles:
      - name: odoo
        https: letsencrypt
        domains: ['www.example.com', 'example.com']
    deployTo:
      - odoo
hosts:
  - name: odoo
    requirements:
      cores: 1
      memory: 1
