version: '1.0'
services:
  - name: db-maxxtools
    type: postgres
    version: 9.6
    configuration: StandAlone
    ports:
      - 5432
    env:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: null
    remoteAccess: false
    deployTo:
      - odoo

  - name: odoo-maxxtools
    type: docker
    image: codeagency/odoo-enterprise
    version: 11.0
    source: git@github.com:codeagencybe/odoo-client-test.git
    branch: master
    ports:
      - 8069
      - 8071
    remoteAccess: false
    env:
      HOST: "{{=service('db-maxxtools').getMasterAlias()}}"
      PORT: "{{=service('db-maxxtools').getMainPort()}}"
      USER: odoo
      PASSWORD: "{{=service('db-maxxtools').getEnv('POSTGRES_PASSWORD')}}"
    volumes:
      - directory: /var/lib/odoo
    volumesUID: 101
    startCommand: --addons $MAIN_PATH,/mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons  -i web_enterprise
    deployTo:
      - odoo

  - name: nginx-maxxtools
    type: nginx
    version: 1.13
    ports:
      - 80
      - 443
    remoteAccess: true
    serviceFiles:
      - name: odoo-maxxtools
    deployTo:
      - odoo
hosts:
  - name: odoo
    requirements:
      cores: 1
      memory: 1
